package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

/**
 * CarConfigDetail generated by hbm2java
 */
public class CarConfigDetail implements java.io.Serializable {

	private Integer id;
	private Integer carId;
	private Integer specId;
	private String url;
	private String baseConfig;
	private String carBody;
	private String carEngine;
	private String carGearBox;
	private String carChassisSteering;
	private String carBraking;
	private String carSecurity;
	private String carControl;
	private String carUnBurglars;
	private String carInnerConfig;
	private String carChairConfig;
	private String carMultiMediaConfig;
	private String carLightConfig;
	private String carWindowConfig;
	private String carAirAndFridge;
	private String carOptionBag;

	public CarConfigDetail() {
	}

	public CarConfigDetail(Integer carId, Integer specId, String url, String baseConfig, String carBody,
			String carEngine, String carGearBox, String carChassisSteering, String carBraking, String carSecurity,
			String carControl, String carUnBurglars, String carInnerConfig, String carChairConfig,
			String carMultiMediaConfig, String carLightConfig, String carWindowConfig, String carAirAndFridge,
			String carOptionBag) {
		this.carId = carId;
		this.specId = specId;
		this.url = url;
		this.baseConfig = baseConfig;
		this.carBody = carBody;
		this.carEngine = carEngine;
		this.carGearBox = carGearBox;
		this.carChassisSteering = carChassisSteering;
		this.carBraking = carBraking;
		this.carSecurity = carSecurity;
		this.carControl = carControl;
		this.carUnBurglars = carUnBurglars;
		this.carInnerConfig = carInnerConfig;
		this.carChairConfig = carChairConfig;
		this.carMultiMediaConfig = carMultiMediaConfig;
		this.carLightConfig = carLightConfig;
		this.carWindowConfig = carWindowConfig;
		this.carAirAndFridge = carAirAndFridge;
		this.carOptionBag = carOptionBag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public Integer getSpecId() {
		return this.specId;
	}

	public void setSpecId(Integer specId) {
		this.specId = specId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getBaseConfig() {
		return this.baseConfig;
	}

	public void setBaseConfig(String baseConfig) {
		this.baseConfig = baseConfig;
	}

	public String getCarBody() {
		return this.carBody;
	}

	public void setCarBody(String carBody) {
		this.carBody = carBody;
	}

	public String getCarEngine() {
		return this.carEngine;
	}

	public void setCarEngine(String carEngine) {
		this.carEngine = carEngine;
	}

	public String getCarGearBox() {
		return this.carGearBox;
	}

	public void setCarGearBox(String carGearBox) {
		this.carGearBox = carGearBox;
	}

	public String getCarChassisSteering() {
		return this.carChassisSteering;
	}

	public void setCarChassisSteering(String carChassisSteering) {
		this.carChassisSteering = carChassisSteering;
	}

	public String getCarBraking() {
		return this.carBraking;
	}

	public void setCarBraking(String carBraking) {
		this.carBraking = carBraking;
	}

	public String getCarSecurity() {
		return this.carSecurity;
	}

	public void setCarSecurity(String carSecurity) {
		this.carSecurity = carSecurity;
	}

	public String getCarControl() {
		return this.carControl;
	}

	public void setCarControl(String carControl) {
		this.carControl = carControl;
	}

	public String getCarUnBurglars() {
		return this.carUnBurglars;
	}

	public void setCarUnBurglars(String carUnBurglars) {
		this.carUnBurglars = carUnBurglars;
	}

	public String getCarInnerConfig() {
		return this.carInnerConfig;
	}

	public void setCarInnerConfig(String carInnerConfig) {
		this.carInnerConfig = carInnerConfig;
	}

	public String getCarChairConfig() {
		return this.carChairConfig;
	}

	public void setCarChairConfig(String carChairConfig) {
		this.carChairConfig = carChairConfig;
	}

	public String getCarMultiMediaConfig() {
		return this.carMultiMediaConfig;
	}

	public void setCarMultiMediaConfig(String carMultiMediaConfig) {
		this.carMultiMediaConfig = carMultiMediaConfig;
	}

	public String getCarLightConfig() {
		return this.carLightConfig;
	}

	public void setCarLightConfig(String carLightConfig) {
		this.carLightConfig = carLightConfig;
	}

	public String getCarWindowConfig() {
		return this.carWindowConfig;
	}

	public void setCarWindowConfig(String carWindowConfig) {
		this.carWindowConfig = carWindowConfig;
	}

	public String getCarAirAndFridge() {
		return this.carAirAndFridge;
	}

	public void setCarAirAndFridge(String carAirAndFridge) {
		this.carAirAndFridge = carAirAndFridge;
	}

	public String getCarOptionBag() {
		return this.carOptionBag;
	}

	public void setCarOptionBag(String carOptionBag) {
		this.carOptionBag = carOptionBag;
	}

}
