package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

/**
 * CarNews generated by hbm2java
 */
public class CarNews implements java.io.Serializable {

	private Integer id;
	private Integer autoArticleId;
	private Integer carId;
	private String title;
	private String url;
	private String reportTime;
	private Integer viewNum;
	private Integer commentNum;
	private String tagInfos;

	public CarNews() {
	}

	public CarNews(Integer autoArticleId, Integer carId, String title, String url, String reportTime, Integer viewNum,
			Integer commentNum, String tagInfos) {
		this.autoArticleId = autoArticleId;
		this.carId = carId;
		this.title = title;
		this.url = url;
		this.reportTime = reportTime;
		this.viewNum = viewNum;
		this.commentNum = commentNum;
		this.tagInfos = tagInfos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAutoArticleId() {
		return this.autoArticleId;
	}

	public void setAutoArticleId(Integer autoArticleId) {
		this.autoArticleId = autoArticleId;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(String reportTime) {
		this.reportTime = reportTime;
	}

	public Integer getViewNum() {
		return this.viewNum;
	}

	public void setViewNum(Integer viewNum) {
		this.viewNum = viewNum;
	}

	public Integer getCommentNum() {
		return this.commentNum;
	}

	public void setCommentNum(Integer commentNum) {
		this.commentNum = commentNum;
	}

	public String getTagInfos() {
		return this.tagInfos;
	}

	public void setTagInfos(String tagInfos) {
		this.tagInfos = tagInfos;
	}

}
