package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CarPost generated by hbm2java
 */
public class CarPost implements java.io.Serializable {

	private Integer id;
	private Integer carId;
	private String url;
	private Integer userId;
	private String title;
	private Date time;
	private String subject;
	private Integer clickNum;
	private Integer viewNum;
	private Date lastReplyTime;

	public CarPost() {
	}

	public CarPost(Integer carId, String url, Integer userId, String title, Date time, String subject, Integer clickNum,
			Integer viewNum, Date lastReplyTime) {
		this.carId = carId;
		this.url = url;
		this.userId = userId;
		this.title = title;
		this.time = time;
		this.subject = subject;
		this.clickNum = clickNum;
		this.viewNum = viewNum;
		this.lastReplyTime = lastReplyTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Integer getClickNum() {
		return this.clickNum;
	}

	public void setClickNum(Integer clickNum) {
		this.clickNum = clickNum;
	}

	public Integer getViewNum() {
		return this.viewNum;
	}

	public void setViewNum(Integer viewNum) {
		this.viewNum = viewNum;
	}

	public Date getLastReplyTime() {
		return this.lastReplyTime;
	}

	public void setLastReplyTime(Date lastReplyTime) {
		this.lastReplyTime = lastReplyTime;
	}

}
