package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

/**
 * CarPrice generated by hbm2java
 */
public class CarPrice implements java.io.Serializable {

	private Integer id;
	private Integer carId;
	private String url;
	private String carPrice;
	private String guidePrice;
	private String recommendCar;

	public CarPrice() {
	}

	public CarPrice(Integer carId, String url, String carPrice, String guidePrice, String recommendCar) {
		this.carId = carId;
		this.url = url;
		this.carPrice = carPrice;
		this.guidePrice = guidePrice;
		this.recommendCar = recommendCar;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getCarPrice() {
		return this.carPrice;
	}

	public void setCarPrice(String carPrice) {
		this.carPrice = carPrice;
	}

	public String getGuidePrice() {
		return this.guidePrice;
	}

	public void setGuidePrice(String guidePrice) {
		this.guidePrice = guidePrice;
	}

	public String getRecommendCar() {
		return this.recommendCar;
	}

	public void setRecommendCar(String recommendCar) {
		this.recommendCar = recommendCar;
	}

}
