package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

/**
 * CarPraise generated by hbm2java
 */
public class CarPraise implements java.io.Serializable {

	private Integer id;
	private Integer carId;
	private Integer praiseNum;
	private String pageUrl;
	private String userScore;
	private String fuelEconomy;
	private String praiseInfoSum;
	private String newCarBreakNum;
	private String oldCarBreakNum;
	private String exteriorBreakNum;
	private String interiorBreakNum;
	private String driveBreakNum;
	private String functionBreakNum;
	private String edbreakNum;
	private String chairBreakNum;
	private String airConBreakNum;
	private String engineBreakNum;
	private String shiftBreakNum;

	public CarPraise() {
	}

	public CarPraise(Integer carId, Integer praiseNum, String pageUrl, String userScore, String fuelEconomy,
			String praiseInfoSum, String newCarBreakNum, String oldCarBreakNum, String exteriorBreakNum,
			String interiorBreakNum, String driveBreakNum, String functionBreakNum, String edbreakNum,
			String chairBreakNum, String airConBreakNum, String engineBreakNum, String shiftBreakNum) {
		this.carId = carId;
		this.praiseNum = praiseNum;
		this.pageUrl = pageUrl;
		this.userScore = userScore;
		this.fuelEconomy = fuelEconomy;
		this.praiseInfoSum = praiseInfoSum;
		this.newCarBreakNum = newCarBreakNum;
		this.oldCarBreakNum = oldCarBreakNum;
		this.exteriorBreakNum = exteriorBreakNum;
		this.interiorBreakNum = interiorBreakNum;
		this.driveBreakNum = driveBreakNum;
		this.functionBreakNum = functionBreakNum;
		this.edbreakNum = edbreakNum;
		this.chairBreakNum = chairBreakNum;
		this.airConBreakNum = airConBreakNum;
		this.engineBreakNum = engineBreakNum;
		this.shiftBreakNum = shiftBreakNum;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public Integer getPraiseNum() {
		return this.praiseNum;
	}

	public void setPraiseNum(Integer praiseNum) {
		this.praiseNum = praiseNum;
	}

	public String getPageUrl() {
		return this.pageUrl;
	}

	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}

	public String getUserScore() {
		return this.userScore;
	}

	public void setUserScore(String userScore) {
		this.userScore = userScore;
	}

	public String getFuelEconomy() {
		return this.fuelEconomy;
	}

	public void setFuelEconomy(String fuelEconomy) {
		this.fuelEconomy = fuelEconomy;
	}

	public String getPraiseInfoSum() {
		return this.praiseInfoSum;
	}

	public void setPraiseInfoSum(String praiseInfoSum) {
		this.praiseInfoSum = praiseInfoSum;
	}

	public String getNewCarBreakNum() {
		return this.newCarBreakNum;
	}

	public void setNewCarBreakNum(String newCarBreakNum) {
		this.newCarBreakNum = newCarBreakNum;
	}

	public String getOldCarBreakNum() {
		return this.oldCarBreakNum;
	}

	public void setOldCarBreakNum(String oldCarBreakNum) {
		this.oldCarBreakNum = oldCarBreakNum;
	}

	public String getExteriorBreakNum() {
		return this.exteriorBreakNum;
	}

	public void setExteriorBreakNum(String exteriorBreakNum) {
		this.exteriorBreakNum = exteriorBreakNum;
	}

	public String getInteriorBreakNum() {
		return this.interiorBreakNum;
	}

	public void setInteriorBreakNum(String interiorBreakNum) {
		this.interiorBreakNum = interiorBreakNum;
	}

	public String getDriveBreakNum() {
		return this.driveBreakNum;
	}

	public void setDriveBreakNum(String driveBreakNum) {
		this.driveBreakNum = driveBreakNum;
	}

	public String getFunctionBreakNum() {
		return this.functionBreakNum;
	}

	public void setFunctionBreakNum(String functionBreakNum) {
		this.functionBreakNum = functionBreakNum;
	}

	public String getEdbreakNum() {
		return this.edbreakNum;
	}

	public void setEdbreakNum(String edbreakNum) {
		this.edbreakNum = edbreakNum;
	}

	public String getChairBreakNum() {
		return this.chairBreakNum;
	}

	public void setChairBreakNum(String chairBreakNum) {
		this.chairBreakNum = chairBreakNum;
	}

	public String getAirConBreakNum() {
		return this.airConBreakNum;
	}

	public void setAirConBreakNum(String airConBreakNum) {
		this.airConBreakNum = airConBreakNum;
	}

	public String getEngineBreakNum() {
		return this.engineBreakNum;
	}

	public void setEngineBreakNum(String engineBreakNum) {
		this.engineBreakNum = engineBreakNum;
	}

	public String getShiftBreakNum() {
		return this.shiftBreakNum;
	}

	public void setShiftBreakNum(String shiftBreakNum) {
		this.shiftBreakNum = shiftBreakNum;
	}

}
