package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CarPraiseDetail generated by hbm2java
 */
public class CarPraiseDetail implements java.io.Serializable {

	private Integer id;
	private Integer carId;
	private String url;
	private String autoUserId;
	private Date praiseDate;
	private String title;
	private String content;
	private String client;
	private Integer authSpecId;
	private String authcarName;
	private Integer buyCarSeriesId;
	private String buyCarCity;
	private String carBearName;
	private Date buyCarDate;
	private String cost;
	private String oilWearSize;
	private String travelDistance;
	private Integer space;
	private Integer engine;
	private Integer carHold;
	private Integer oilWear;
	private Integer comfortable;
	private Integer exterior;
	private Integer interior;
	private Integer costPer;
	private String goal;

	public CarPraiseDetail() {
	}

	public CarPraiseDetail(Integer carId, String url, String autoUserId, Date praiseDate, String title, String content,
			String client, Integer authSpecId, String authcarName, Integer buyCarSeriesId, String buyCarCity,
			String carBearName, Date buyCarDate, String cost, String oilWearSize, String travelDistance, Integer space,
			Integer engine, Integer carHold, Integer oilWear, Integer comfortable, Integer exterior, Integer interior,
			Integer costPer, String goal) {
		this.carId = carId;
		this.url = url;
		this.autoUserId = autoUserId;
		this.praiseDate = praiseDate;
		this.title = title;
		this.content = content;
		this.client = client;
		this.authSpecId = authSpecId;
		this.authcarName = authcarName;
		this.buyCarSeriesId = buyCarSeriesId;
		this.buyCarCity = buyCarCity;
		this.carBearName = carBearName;
		this.buyCarDate = buyCarDate;
		this.cost = cost;
		this.oilWearSize = oilWearSize;
		this.travelDistance = travelDistance;
		this.space = space;
		this.engine = engine;
		this.carHold = carHold;
		this.oilWear = oilWear;
		this.comfortable = comfortable;
		this.exterior = exterior;
		this.interior = interior;
		this.costPer = costPer;
		this.goal = goal;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getAutoUserId() {
		return this.autoUserId;
	}

	public void setAutoUserId(String autoUserId) {
		this.autoUserId = autoUserId;
	}

	public Date getPraiseDate() {
		return this.praiseDate;
	}

	public void setPraiseDate(Date praiseDate) {
		this.praiseDate = praiseDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	public Integer getAuthSpecId() {
		return this.authSpecId;
	}

	public void setAuthSpecId(Integer authSpecId) {
		this.authSpecId = authSpecId;
	}

	public String getAuthcarName() {
		return this.authcarName;
	}

	public void setAuthcarName(String authcarName) {
		this.authcarName = authcarName;
	}

	public Integer getBuyCarSeriesId() {
		return this.buyCarSeriesId;
	}

	public void setBuyCarSeriesId(Integer buyCarSeriesId) {
		this.buyCarSeriesId = buyCarSeriesId;
	}

	public String getBuyCarCity() {
		return this.buyCarCity;
	}

	public void setBuyCarCity(String buyCarCity) {
		this.buyCarCity = buyCarCity;
	}

	public String getCarBearName() {
		return this.carBearName;
	}

	public void setCarBearName(String carBearName) {
		this.carBearName = carBearName;
	}

	public Date getBuyCarDate() {
		return this.buyCarDate;
	}

	public void setBuyCarDate(Date buyCarDate) {
		this.buyCarDate = buyCarDate;
	}

	public String getCost() {
		return this.cost;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}

	public String getOilWearSize() {
		return this.oilWearSize;
	}

	public void setOilWearSize(String oilWearSize) {
		this.oilWearSize = oilWearSize;
	}

	public String getTravelDistance() {
		return this.travelDistance;
	}

	public void setTravelDistance(String travelDistance) {
		this.travelDistance = travelDistance;
	}

	public Integer getSpace() {
		return this.space;
	}

	public void setSpace(Integer space) {
		this.space = space;
	}

	public Integer getEngine() {
		return this.engine;
	}

	public void setEngine(Integer engine) {
		this.engine = engine;
	}

	public Integer getCarHold() {
		return this.carHold;
	}

	public void setCarHold(Integer carHold) {
		this.carHold = carHold;
	}

	public Integer getOilWear() {
		return this.oilWear;
	}

	public void setOilWear(Integer oilWear) {
		this.oilWear = oilWear;
	}

	public Integer getComfortable() {
		return this.comfortable;
	}

	public void setComfortable(Integer comfortable) {
		this.comfortable = comfortable;
	}

	public Integer getExterior() {
		return this.exterior;
	}

	public void setExterior(Integer exterior) {
		this.exterior = exterior;
	}

	public Integer getInterior() {
		return this.interior;
	}

	public void setInterior(Integer interior) {
		this.interior = interior;
	}

	public Integer getCostPer() {
		return this.costPer;
	}

	public void setCostPer(Integer costPer) {
		this.costPer = costPer;
	}

	public String getGoal() {
		return this.goal;
	}

	public void setGoal(String goal) {
		this.goal = goal;
	}

}
