package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CarQuestion generated by hbm2java
 */
public class CarQuestion implements java.io.Serializable {

	private Integer id;
	private Integer carId;
	private String url;
	private String title;
	private String content;
	private Integer subjectId;
	private Date time;
	private String userId;
	private Integer checkNum;

	public CarQuestion() {
	}

	public CarQuestion(Integer carId, String url, String title, String content, Integer subjectId, Date time,
			String userId, Integer checkNum) {
		this.carId = carId;
		this.url = url;
		this.title = title;
		this.content = content;
		this.subjectId = subjectId;
		this.time = time;
		this.userId = userId;
		this.checkNum = checkNum;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getCheckNum() {
		return this.checkNum;
	}

	public void setCheckNum(Integer checkNum) {
		this.checkNum = checkNum;
	}

}
