package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

/**
 * CarSeriesPicDetail generated by hbm2java
 */
public class CarSeriesPicDetail implements java.io.Serializable {

	private Integer id;
	private Integer carId;
	private Integer autoSeriesId;
	private Integer year;
	private String name;
	private Integer picNum;
	private String carSeriesPicUrl;

	public CarSeriesPicDetail() {
	}

	public CarSeriesPicDetail(Integer carId, Integer autoSeriesId, Integer year, String name, Integer picNum,
			String carSeriesPicUrl) {
		this.carId = carId;
		this.autoSeriesId = autoSeriesId;
		this.year = year;
		this.name = name;
		this.picNum = picNum;
		this.carSeriesPicUrl = carSeriesPicUrl;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public Integer getAutoSeriesId() {
		return this.autoSeriesId;
	}

	public void setAutoSeriesId(Integer autoSeriesId) {
		this.autoSeriesId = autoSeriesId;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getPicNum() {
		return this.picNum;
	}

	public void setPicNum(Integer picNum) {
		this.picNum = picNum;
	}

	public String getCarSeriesPicUrl() {
		return this.carSeriesPicUrl;
	}

	public void setCarSeriesPicUrl(String carSeriesPicUrl) {
		this.carSeriesPicUrl = carSeriesPicUrl;
	}

}
