package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * QuestionResponse generated by hbm2java
 */
public class QuestionResponse implements java.io.Serializable {

	private Integer id;
	private Integer questionId;
	private String questionUrl;
	private String userId;
	private Integer replyFloor;
	private Integer floor;
	private Integer isAccept;
	private Date time;
	private String content;

	public QuestionResponse() {
	}

	public QuestionResponse(Integer questionId, String questionUrl, String userId, Integer replyFloor, Integer floor,
			Integer isAccept, Date time, String content) {
		this.questionId = questionId;
		this.questionUrl = questionUrl;
		this.userId = userId;
		this.replyFloor = replyFloor;
		this.floor = floor;
		this.isAccept = isAccept;
		this.time = time;
		this.content = content;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	public String getQuestionUrl() {
		return this.questionUrl;
	}

	public void setQuestionUrl(String questionUrl) {
		this.questionUrl = questionUrl;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getReplyFloor() {
		return this.replyFloor;
	}

	public void setReplyFloor(Integer replyFloor) {
		this.replyFloor = replyFloor;
	}

	public Integer getFloor() {
		return this.floor;
	}

	public void setFloor(Integer floor) {
		this.floor = floor;
	}

	public Integer getIsAccept() {
		return this.isAccept;
	}

	public void setIsAccept(Integer isAccept) {
		this.isAccept = isAccept;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
