package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Integer id;
	private String autoUserId;
	private String url;
	private String name;
	private String sex;
	private Date birthday;
	private String phoneAuth;
	private String city;
	private Integer followingNum;
	private Integer followerNum;
	private Integer helpScore;
	private Integer bestPostNum;
	private Integer postNum;
	private String ownCarList;

	public UserInfo() {
	}

	public UserInfo(String autoUserId, String url, String name, String sex, Date birthday, String phoneAuth,
			String city, Integer followingNum, Integer followerNum, Integer helpScore, Integer bestPostNum,
			Integer postNum, String ownCarList) {
		this.autoUserId = autoUserId;
		this.url = url;
		this.name = name;
		this.sex = sex;
		this.birthday = birthday;
		this.phoneAuth = phoneAuth;
		this.city = city;
		this.followingNum = followingNum;
		this.followerNum = followerNum;
		this.helpScore = helpScore;
		this.bestPostNum = bestPostNum;
		this.postNum = postNum;
		this.ownCarList = ownCarList;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAutoUserId() {
		return this.autoUserId;
	}

	public void setAutoUserId(String autoUserId) {
		this.autoUserId = autoUserId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getPhoneAuth() {
		return this.phoneAuth;
	}

	public void setPhoneAuth(String phoneAuth) {
		this.phoneAuth = phoneAuth;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Integer getFollowingNum() {
		return this.followingNum;
	}

	public void setFollowingNum(Integer followingNum) {
		this.followingNum = followingNum;
	}

	public Integer getFollowerNum() {
		return this.followerNum;
	}

	public void setFollowerNum(Integer followerNum) {
		this.followerNum = followerNum;
	}

	public Integer getHelpScore() {
		return this.helpScore;
	}

	public void setHelpScore(Integer helpScore) {
		this.helpScore = helpScore;
	}

	public Integer getBestPostNum() {
		return this.bestPostNum;
	}

	public void setBestPostNum(Integer bestPostNum) {
		this.bestPostNum = bestPostNum;
	}

	public Integer getPostNum() {
		return this.postNum;
	}

	public void setPostNum(Integer postNum) {
		this.postNum = postNum;
	}

	public String getOwnCarList() {
		return this.ownCarList;
	}

	public void setOwnCarList(String ownCarList) {
		this.ownCarList = ownCarList;
	}

}
