package com.chance.crawlerProject.autohome.bean;
// Generated 2018-1-12 17:58:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * UserCar generated by hbm2java
 */
public class UserCar implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private String carUrl;
	private String carName;
	private String guidePrice;
	private String costAllPrice;
	private String carPrice;
	private String purchaseTax;
	private String compulsoryInsurance;
	private String vavut;
	private String commercialInsurance;
	private String licenseFee;
	private String payType;
	private String downPaymentPrice;
	private String repaymentNum;
	private String serviceFee;
	private String promotionGoods;
	private Date buyCarTime;
	private String city;
	private String manufactorInfo;
	private String saleTips;

	public UserCar() {
	}

	public UserCar(Integer userId, String carUrl, String carName, String guidePrice, String costAllPrice,
			String carPrice, String purchaseTax, String compulsoryInsurance, String vavut, String commercialInsurance,
			String licenseFee, String payType, String downPaymentPrice, String repaymentNum, String serviceFee,
			String promotionGoods, Date buyCarTime, String city, String manufactorInfo, String saleTips) {
		this.userId = userId;
		this.carUrl = carUrl;
		this.carName = carName;
		this.guidePrice = guidePrice;
		this.costAllPrice = costAllPrice;
		this.carPrice = carPrice;
		this.purchaseTax = purchaseTax;
		this.compulsoryInsurance = compulsoryInsurance;
		this.vavut = vavut;
		this.commercialInsurance = commercialInsurance;
		this.licenseFee = licenseFee;
		this.payType = payType;
		this.downPaymentPrice = downPaymentPrice;
		this.repaymentNum = repaymentNum;
		this.serviceFee = serviceFee;
		this.promotionGoods = promotionGoods;
		this.buyCarTime = buyCarTime;
		this.city = city;
		this.manufactorInfo = manufactorInfo;
		this.saleTips = saleTips;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getCarUrl() {
		return this.carUrl;
	}

	public void setCarUrl(String carUrl) {
		this.carUrl = carUrl;
	}

	public String getCarName() {
		return this.carName;
	}

	public void setCarName(String carName) {
		this.carName = carName;
	}

	public String getGuidePrice() {
		return this.guidePrice;
	}

	public void setGuidePrice(String guidePrice) {
		this.guidePrice = guidePrice;
	}

	public String getCostAllPrice() {
		return this.costAllPrice;
	}

	public void setCostAllPrice(String costAllPrice) {
		this.costAllPrice = costAllPrice;
	}

	public String getCarPrice() {
		return this.carPrice;
	}

	public void setCarPrice(String carPrice) {
		this.carPrice = carPrice;
	}

	public String getPurchaseTax() {
		return this.purchaseTax;
	}

	public void setPurchaseTax(String purchaseTax) {
		this.purchaseTax = purchaseTax;
	}

	public String getCompulsoryInsurance() {
		return this.compulsoryInsurance;
	}

	public void setCompulsoryInsurance(String compulsoryInsurance) {
		this.compulsoryInsurance = compulsoryInsurance;
	}

	public String getVavut() {
		return this.vavut;
	}

	public void setVavut(String vavut) {
		this.vavut = vavut;
	}

	public String getCommercialInsurance() {
		return this.commercialInsurance;
	}

	public void setCommercialInsurance(String commercialInsurance) {
		this.commercialInsurance = commercialInsurance;
	}

	public String getLicenseFee() {
		return this.licenseFee;
	}

	public void setLicenseFee(String licenseFee) {
		this.licenseFee = licenseFee;
	}

	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public String getDownPaymentPrice() {
		return this.downPaymentPrice;
	}

	public void setDownPaymentPrice(String downPaymentPrice) {
		this.downPaymentPrice = downPaymentPrice;
	}

	public String getRepaymentNum() {
		return this.repaymentNum;
	}

	public void setRepaymentNum(String repaymentNum) {
		this.repaymentNum = repaymentNum;
	}

	public String getServiceFee() {
		return this.serviceFee;
	}

	public void setServiceFee(String serviceFee) {
		this.serviceFee = serviceFee;
	}

	public String getPromotionGoods() {
		return this.promotionGoods;
	}

	public void setPromotionGoods(String promotionGoods) {
		this.promotionGoods = promotionGoods;
	}

	public Date getBuyCarTime() {
		return this.buyCarTime;
	}

	public void setBuyCarTime(Date buyCarTime) {
		this.buyCarTime = buyCarTime;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getManufactorInfo() {
		return this.manufactorInfo;
	}

	public void setManufactorInfo(String manufactorInfo) {
		this.manufactorInfo = manufactorInfo;
	}

	public String getSaleTips() {
		return this.saleTips;
	}

	public void setSaleTips(String saleTips) {
		this.saleTips = saleTips;
	}

}
